/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.karimandco.auth;

import java.awt.Color;
import javax.swing.JLabel;

/**
 *
 * @author Damien F, Pawel R, Théo M
 */
public class PanneauChamp extends javax.swing.JPanel {

    /**
     * Creates new form PanneauChampSecret
     */
    public PanneauChamp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelEtatChamp = new javax.swing.JLabel();
        jLabelNomChamp = new javax.swing.JLabel();
        champ2 = new com.karimandco.auth.Champ();

        jLabelEtatChamp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabelNomChamp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNomChamp.setText("champ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelNomChamp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(champ2, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                            .addComponent(jLabelEtatChamp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelNomChamp, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(champ2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelEtatChamp, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    public Champ getChamp2() {
        return champ2;
    }

    public void setChamp2(Champ champ2) {
        this.champ2 = champ2;
    }

    public JLabel getjLabelEtatChamp() {
        return jLabelEtatChamp;
    }

    public void setjLabelEtatChamp(JLabel jLabelEtatChamp) {
        this.jLabelEtatChamp = jLabelEtatChamp;
    }

    public void setjLabelEtatChamp(String nom) {
        this.jLabelEtatChamp.setText(nom);
    }

    public void setjLabelEtatChamp(Color couleur) {
        this.jLabelEtatChamp.setForeground(couleur);
    }

    public JLabel getjLabelNomChamp() {
        return jLabelNomChamp;
    }

    public void setjLabelNomChamp(JLabel jLabelNomChamp) {
        this.jLabelNomChamp = jLabelNomChamp;
    }

    public void setjLabelNomChamp(String nom) {
        this.jLabelNomChamp.setText(nom);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.karimandco.auth.Champ champ2;
    private javax.swing.JLabel jLabelEtatChamp;
    private javax.swing.JLabel jLabelNomChamp;
    // End of variables declaration//GEN-END:variables
}
